-- Creates the 'profiles' table linked to Supabase auth.users
--
-- Columns: id (uuid PK, FK → auth.users), username (unique), location, preferences,
--          email, phone, preferred_communication, role, vet_clinic_name, vet_clinic_phone,
--          vet_clinic_address, created_at
--
-- RLS policies:
--   SELECT: authenticated users can read all profiles
--   UPDATE: users can only update their own row (auth.uid() = id)
--
-- Trigger: auto-insert into profiles on auth.users INSERT
--
-- Satisfies: RQ1, RQ26, RQ28, RQ29, RQ32, NF7 (UK GDPR — RLS enforced)
